import type { GridLine, MissingNumberData, NumerologyReport, PersonalYearData } from './numerology';

interface ProfileCopy {
  personality: string;
  emotional: string;
  wealth: string;
  soul: string;
  chakra: string;
  description: string;
}

const LIFE_PATH_EN: Record<number, ProfileCopy> = {
  1: { personality: 'Leader, pioneer, and independent thinker', emotional: 'May prefer independence and find it difficult to ask for support', wealth: 'Can build resources through initiative and self-directed work', soul: 'Practice independence while staying connected to others', chakra: 'Solar Plexus', description: 'Your profile is associated with initiative, courage, and creating new directions. You may feel engaged when you can act on ideas and make thoughtful choices for yourself. Balance self-reliance with collaboration: accepting support does not diminish your leadership.' },
  2: { personality: 'Diplomatic, cooperative, and perceptive', emotional: 'Sensitive to the atmosphere around you and may need time to reset', wealth: 'Can build resources through collaboration and shared strengths', soul: 'Balance giving, receiving, and honoring your own needs', chakra: 'Heart', description: 'Your profile is associated with cooperation, careful listening, and sensitivity to relationships. These qualities can support thoughtful collaboration when paired with clear boundaries. Let your preferences count alongside the needs of people around you.' },
  3: { personality: 'Creative, expressive, and optimistic', emotional: 'May benefit from creative outlets and honest communication', wealth: 'Can use creativity, communication, and adaptable skills', soul: 'Express yourself sincerely rather than shaping every choice to please others', chakra: 'Throat', description: 'Your profile is associated with imagination, communication, and creative expression. Writing, speaking, art, or playful experimentation may help you make sense of experience. Expression can be valuable for its own sake; let your ideas develop over time.' },
  4: { personality: 'Practical, dependable, and methodical', emotional: 'May focus on tasks when feelings feel difficult to approach', wealth: 'Can build stability through consistent effort and useful systems', soul: 'Create dependable routines while remaining open to change', chakra: 'Root', description: 'Your profile is associated with structure, patience, and turning plans into practical steps. Stability can be a strength when it leaves room for rest, flexibility, and emotional awareness. Choose systems that support your life rather than standards that make you feel trapped.' },
  5: { personality: 'Curious, adaptable, and adventurous', emotional: 'May feel restless when choices or routines seem restrictive', wealth: 'Can draw on adaptability, communication, and varied experience', soul: 'Make room for freedom while honoring chosen responsibilities', chakra: 'Sacral', description: 'Your profile is associated with curiosity, adaptability, and learning through experience. New ideas and environments may energize you, while too many commitments can scatter attention. Explore without deciding everything at once, and give a chosen direction time.' },
  6: { personality: 'Caring, responsible, and community-minded', emotional: 'May give more than you have energy to sustain', wealth: 'Can build value through service, care, and creative work', soul: 'Include yourself in the care you offer to others', chakra: 'Heart', description: 'Your profile is associated with care, responsibility, and a desire to contribute. People may turn to you for support. Sustainable care includes your own needs, limits, and recovery time; you do not have to take responsibility for everything around you.' },
  7: { personality: 'Analytical, reflective, and curious', emotional: 'May keep feelings private or need time before trusting', wealth: 'Can draw on research, specialized knowledge, and analysis', soul: 'Combine independent reflection with meaningful connection', chakra: 'Crown', description: 'Your profile is associated with reflection, research, and a desire to understand how things work. Quiet time may help organize ideas, while trusted conversations offer new perspectives. Give both evidence and lived experience a place in your thinking.' },
  8: { personality: 'Strategic, determined, and capable of managing resources', emotional: 'May find vulnerability or sharing control challenging', wealth: 'Can use planning, leadership, and business skills thoughtfully', soul: 'Use influence responsibly without trying to control others', chakra: 'Solar Plexus', description: 'Your profile is associated with organization, ambition, and working with resources and responsibility. Long-term success can include integrity, collaboration, and well-being, not only status or financial outcomes. Consider how your decisions affect your values and other people.' },
  9: { personality: 'Compassionate, thoughtful, and broadly minded', emotional: 'May hold on to past experiences or take on others’ distress', wealth: 'Can find meaning in service, education, and purpose-led work', soul: 'Practice letting go while maintaining compassionate boundaries', chakra: 'Crown', description: 'Your profile is associated with compassion, perspective, and concern for others. Compassion does not require carrying every problem yourself. Make room for your own priorities and acknowledge endings without letting them define your future.' },
  11: { personality: 'Inspired, perceptive, and imaginative', emotional: 'May feel overstimulated and benefit from grounding routines', wealth: 'Can share ideas through teaching, creative work, or encouragement', soul: 'Balance intuition with practical checks and steady care', chakra: 'Third Eye', description: 'Your profile is associated with imagination, sensitivity, and noticing subtle patterns. These can be useful prompts for reflection, though a first impression is not complete evidence. Ground ideas in observation, rest, and practical testing.' },
  22: { personality: 'Organized, visionary, and implementation-focused', emotional: 'May feel pressure to carry too much responsibility', wealth: 'Can build useful systems through planning and collaboration', soul: 'Break ambitious ideas into realistic steps and ask for support', chakra: 'Integrated', description: 'Your profile is associated with combining long-range thinking and practical organization. Large goals become more manageable when divided into steps, resources, and review points. Your contribution does not need to be enormous to be meaningful.' },
  33: { personality: 'Compassionate, supportive, and service-oriented', emotional: 'May absorb others’ difficulties or neglect personal limits', wealth: 'Can create value through care, education, and community work', soul: 'Offer care without sacrificing your own well-being', chakra: 'Integrated Heart', description: 'Your profile is associated with empathy, support, and a wish to help others grow. Care is most sustainable when it includes consent, realistic boundaries, and attention to your own needs. You can be supportive without solving another person’s problems.' },
};

export function localizeNumerologyReport(report: NumerologyReport): NumerologyReport {
  const copy = LIFE_PATH_EN[report.lifePathNumber];
  if (!copy) return report;
  return { ...report, personality: copy.personality, emotionalPattern: copy.emotional, wealthEnergy: copy.wealth, soulLesson: copy.soul, chakra: copy.chakra, lifePathDescription: copy.description };
}

const GRID_LINE_EN: Record<string, Pick<GridLine, 'name' | 'tag' | 'soulBlueprint' | 'analysis' | 'crystalPrescription' | 'ritual' | 'energyAdvice' | 'crystalEnergy'>> = {
  '1-2-3': { name: 'Creativity and Expression', tag: 'The Creative Communicator', soulBlueprint: 'This line combines initiative, sensitivity, and expression. It can support original ideas when you have room to experiment.', analysis: 'Your numbers suggest initiative, empathy, and creativity. These qualities may be useful in communication or original work.', crystalPrescription: 'Colorful stones can be personal reminders to make space for creativity. They do not guarantee energy changes.', ritual: 'Set aside a short, low-pressure period to write, draw, or make something. Let the first version be imperfect.', energyAdvice: 'Try a creative activity and notice which parts feel engaging.', crystalEnergy: 'Reflection and expression' },
  '4-5-6': { name: 'Organization and Care', tag: 'The Practical Supporter', soulBlueprint: 'This line brings together structure, communication, and care. Being dependable does not mean taking on every responsibility.', analysis: 'Your profile points to organization and support. Clear limits help make these strengths sustainable.', crystalPrescription: 'Green stones can be personal reminders to balance care for others with care for yourself.', ritual: 'Review one commitment and decide whether it still fits your priorities. Consider asking someone to share the work.', energyAdvice: 'Build routines that leave space for rest.', crystalEnergy: 'Care and balance' },
  '7-8-9': { name: 'Wisdom and Resources', tag: 'The Thoughtful Strategist', soulBlueprint: 'This line combines reflection, resource management, and broad perspective. Keep practical evidence and effects on others in view.', analysis: 'Your profile suggests analytical ability and resource awareness alongside compassion.', crystalPrescription: 'Earth-toned or clear stones can remind you to combine big-picture ideas with realistic plans.', ritual: 'Choose a goal, list the resources it needs, and identify one step to take this week.', energyAdvice: 'Balance ambition with practical checks and rest.', crystalEnergy: 'Grounding and perspective' },
  '1-4-7': { name: 'Action and Practicality', tag: 'The Grounded Builder', soulBlueprint: 'This line combines initiative, structure, and analysis. Flexibility can help keep progress sustainable.', analysis: 'Your profile suggests determination and a preference for concrete steps.', crystalPrescription: 'Grounding objects may mark planning time, but they do not replace a plan or advice.', ritual: 'Break a large project into a first step that can be completed in a short session.', energyAdvice: 'Use structure to support progress, not demand perfection.', crystalEnergy: 'Stability and action' },
  '2-5-8': { name: 'Relationships and Communication', tag: 'The Empathetic Communicator', soulBlueprint: 'This line connects sensitivity and influence. Clear communication and boundaries support mutual connection.', analysis: 'Your profile suggests empathy and social awareness. Check assumptions and ask direct questions.', crystalPrescription: 'Blue or rose-colored stones can remind you to speak clearly and treat yourself with care.', ritual: 'Before a difficult conversation, write what you need to communicate and what boundary matters.', energyAdvice: 'Practice asking for what you need as clearly as you offer support.', crystalEnergy: 'Communication and care' },
  '3-6-9': { name: 'Learning and Ideals', tag: 'The Purposeful Learner', soulBlueprint: 'This line brings creativity and broad ideals together. Practical routines can help ideas fit real circumstances.', analysis: 'Your profile suggests imagination and social concern. Let evidence and manageable steps guide your ideas.', crystalPrescription: 'Blue stones can remind you to connect ideas with clear communication.', ritual: 'Write down one ideal and identify a realistic way to express it this week.', energyAdvice: 'Pair long-range values with practical steps and room for revision.', crystalEnergy: 'Clarity and purpose' },
  '1-5-9': { name: 'Initiative and Ambition', tag: 'The Independent Starter', soulBlueprint: 'This line combines initiative and adaptability. Pace your effort and make time to listen as well as lead.', analysis: 'Your profile suggests drive to start projects. Sustainable progress includes breaks and realistic expectations.', crystalPrescription: 'Warm-colored stones can remind you to focus on one priority.', ritual: 'Choose one project, define its next milestone, and review what you learn.', energyAdvice: 'Ambition can work alongside rest and collaboration.', crystalEnergy: 'Focus and initiative' },
  '3-5-7': { name: 'Reflection and Imagination', tag: 'The Curious Observer', soulBlueprint: 'This line combines creativity, adaptability, and reflection. Test ideas and distinguish possibility from established fact.', analysis: 'Your profile suggests curiosity. Pair creative exploration with evidence and daily experience.', crystalPrescription: 'Purple stones can be personal reminders to pause and reflect.', ritual: 'Write down an idea and what you know. Separate observations from interpretations.', energyAdvice: 'Let imagination open questions, and evidence help evaluate answers.', crystalEnergy: 'Reflection and curiosity' },
};

export function localizeGridLine(line: GridLine): GridLine {
  const copy = GRID_LINE_EN[line.id];
  const crystalNames: Record<string, string> = {
    '高頻紫水晶': 'Amethyst', '紫水晶': 'Amethyst', '透石膏': 'Selenite', '祖母綠': 'Emerald', '祖母綠掌中石': 'Emerald',
    '綠色電氣石': 'Green Tourmaline', '骨幹水晶': 'Skeletal Quartz', '深色骨幹水晶': 'Skeletal Quartz', '黃水晶': 'Citrine',
    '紅石榴石': 'Garnet', '黑曜石': 'Obsidian', '白水晶': 'Clear Quartz', '海藍寶': 'Aquamarine', '粉晶': 'Rose Quartz',
    '孔雀石': 'Malachite', '青金石': 'Lapis Lazuli', '拉長石': 'Labradorite', '黑碧璽': 'Black Tourmaline',
    '超級七': 'Super Seven', '鈦晶': 'Rutilated Quartz', '太陽石': 'Sunstone', '金太陽': 'Golden Sunstone',
    '茶晶': 'Smoky Quartz', '東菱玉': 'Green Aventurine', '綠幽靈': 'Green Phantom Quartz', '紅瑪瑙': 'Red Agate',
    '橄欖石': 'Peridot', '月光石': 'Moonstone', '螢石': 'Fluorite', '藍紋瑪瑙': 'Blue Lace Agate',
  };
  return copy
    ? { ...line, ...copy, crystals: line.crystals.map((crystal) => crystalNames[crystal] ?? 'Selected crystal') }
    : line;
}

const MISSING_NUMBER_EN: Record<number, Pick<MissingNumberData, 'traits' | 'challenge' | 'blindspot' | 'crystalFix' | 'affirmation'>> = {
  1: { traits: ['Hesitation', 'Low self-direction', 'Difficulty asserting preferences'], challenge: 'Confidence and initiative', blindspot: 'You may find yourself waiting for permission, reassurance, or the perfect conditions before taking a step. When a decision is yours to make, it can feel safer to let someone else choose, even when you already have a preference. Over time, this habit may make your own direction harder to hear and leave you following expectations that do not fit. This is a reflection prompt, not a fixed trait: confidence can grow through small, reversible choices. Try naming what you want, making one low-risk decision without polling everyone, and noticing what you learn. You can ask for advice while still keeping responsibility for the final choice. Self-direction does not require doing everything alone; it means allowing your own perspective to count.', crystalFix: 'These stones can be personal reminders to make room for clear, self-directed choices:', affirmation: 'I can make a thoughtful choice and take one step forward.' },
  2: { traits: ['Difficulty cooperating', 'Impatience', 'Trouble receiving support'], challenge: 'Cooperation and emotional awareness', blindspot: 'You may notice a relationship’s practical details more easily than its quieter emotional cues, or find it uncomfortable to say that you need support. At other times, you might work hard to keep the peace and then feel depleted or resentful because your own limits were not included. Both patterns can make connection feel like a strain rather than an exchange. Consider asking a simple, open question, listening without immediately fixing the situation, and stating what you can realistically offer. Also practice receiving help without feeling that you must repay it at once. Cooperation is not self-erasure, and independence does not mean refusing care. Clear communication and mutual boundaries can make closeness safer for everyone involved.', crystalFix: 'These stones can remind you to balance listening with your own needs:', affirmation: 'I can listen, share, and keep healthy boundaries.' },
  3: { traits: ['Hesitant self-expression', 'Creative inhibition', 'Communication anxiety'], challenge: 'Expression and creativity', blindspot: 'You may have ideas, feelings, or observations that are vivid inside but difficult to share aloud. An inner critic can start editing before you have finished a thought: worrying about being misunderstood, sounding imperfect, or attracting unwanted attention. If this happens often, you may hold back at work or in relationships and then feel that others do not know what matters to you. Expression can be practiced gradually; it does not have to mean public performance or sharing everything. Try writing privately, telling one trusted person what you really think, or making something without judging the result. Notice which settings help you feel safe enough to speak. Your voice can develop at its own pace, and creativity can be useful even when nobody else sees the finished work.', crystalFix: 'These stones can remind you to express ideas with clarity and care:', affirmation: 'My voice matters, and I can express myself at my own pace.' },
  4: { traits: ['Inconsistent routines', 'Difficulty following plans', 'Uncertainty about stability'], challenge: 'Structure and follow-through', blindspot: 'You may struggle to turn a good intention into a routine, especially when plans are too ambitious or depend on having a perfect week. Starting over repeatedly can create the impression that you lack discipline, when the system itself may simply be too complicated or poorly matched to your life. Uncertainty about money, time, or the future can also make it harder to feel settled, even when some things are going well. Instead of building a rigid schedule, choose one small action with a clear cue and a realistic duration. Review it after a few days and adjust without treating a missed day as failure. Practical stability is built through supports that can flex with changing responsibilities, not through constant control.', crystalFix: 'These stones can remind you of steadiness while you build practical routines:', affirmation: 'I build stability through small, manageable steps.' },
  5: { traits: ['Resistance to change', 'Difficulty adapting', 'Scattered attention'], challenge: 'Flexibility and exploration', blindspot: 'Change can bring up two opposite reactions: holding tightly to what is familiar, or moving quickly between options so that no direction has time to develop. You may delay a useful change while waiting for certainty, then feel restless and try to change everything at once. Either pattern can make it difficult to tell whether you are choosing freely or reacting to discomfort. Treat flexibility as a skill that includes both exploration and follow-through. Try a small experiment with a clear time limit, such as testing a new routine for one week before deciding whether to continue. Keep commitments that still matter, and give yourself permission to revise the ones that do not. Curiosity works best when paired with enough structure to learn from experience.', crystalFix: 'These stones can remind you to stay curious while making grounded choices:', affirmation: 'I can explore new options and adjust as I learn.' },
  6: { traits: ['Difficulty accepting care', 'Uneven giving and receiving', 'Self-criticism'], challenge: 'Care, responsibility, and self-worth', blindspot: 'You may feel responsible for noticing and meeting everyone else’s needs, while treating your own rest or support as optional. This can lead to overcommitting, quiet frustration, or the belief that you must be useful to deserve affection. The opposite response is also possible: keeping people at a distance because receiving care feels unfamiliar or creates a sense of obligation. Neither pattern defines your capacity to love. Try checking your energy before agreeing to help, asking directly for one specific form of support, and noticing whether you can accept it without immediately minimizing your need. Care becomes more sustainable when it includes you. You can be generous and compassionate while keeping limits, sharing responsibility, and allowing relationships to be reciprocal.', crystalFix: 'These stones can remind you to include yourself in the care you offer:', affirmation: 'I deserve care and can support others without abandoning my needs.' },
  7: { traits: ['Overthinking', 'Difficulty trusting uncertainty', 'Need for solitude'], challenge: 'Reflection and trust in your judgment', blindspot: 'When something is uncertain, you may try to think your way to complete certainty by researching, comparing, and replaying every possibility. Analysis can be valuable, but beyond a point it may increase doubt and make it harder to notice what your experience is telling you. You might also dismiss a quiet intuition because you cannot yet explain it, or avoid solitude even when a pause would help you hear yourself. You do not need to choose between evidence and reflection. Set a reasonable limit for gathering information, write down what is known and unknown, then take time away from the question before revisiting it. A trusted conversation can add perspective without deciding for you. Let conclusions remain open to revision as new information appears.', crystalFix: 'These stones can remind you to pause and consider multiple perspectives:', affirmation: 'I can reflect carefully and remain open to what I learn.' },
  8: { traits: ['Difficulty valuing your work', 'Anxiety about resources', 'Hesitation with responsibility'], challenge: 'Resources and practical goals', blindspot: 'Questions about money, achievement, authority, or responsibility may bring up a sense that there will never be enough or that you are not ready to take up space. You might undervalue your work, avoid negotiating, or accept arrangements that ask more of you than they return. At the other extreme, pressure to prove your capability can lead to taking on too much or trying to control every outcome. These responses are worth noticing, not judging. Use concrete information to understand your options: document your time and contribution, compare terms, set a realistic budget, and seek qualified advice for consequential financial choices. Your worth is not measured by income or status. Sustainable goals can include fair exchange, collaboration, rest, and values you want your resources to support.', crystalFix: 'These stones can remind you to approach resources with clarity and realistic planning:', affirmation: 'I can value my work and make grounded decisions about resources.' },
  9: { traits: ['Difficulty letting go', 'Narrow perspective under stress', 'Carrying others’ concerns'], challenge: 'Perspective, completion, and compassion', blindspot: 'When you are hurt or under pressure, attention may become fixed on what went wrong, what should have happened, or what another person ought to understand. It can be hard to forgive yourself or someone else, and you may carry concerns that are not yours to solve. Letting go does not mean excusing harm, forgetting an important lesson, or rushing reconciliation. It can begin by naming what happened, identifying what remains within your control, and deciding what boundary or support you need now. Compassion can include accountability and distance. Try separating a past event from the choices available to you today, and allow grief or anger to take time. A wider perspective is not a demand to feel positive; it is room to recognize your needs, other people’s limits, and the next step you can actually take.', crystalFix: 'These stones can remind you to keep perspective and practice compassionate boundaries:', affirmation: 'I can honor the past while choosing what to carry forward.' },
};

export function localizeMissingNumberData(data: MissingNumberData): MissingNumberData {
  const copy = MISSING_NUMBER_EN[data.number];
  if (!copy) return data;
  return { ...data, ...copy, crystals: data.crystals.map((crystal) => ({
    ...crystal,
    nameZh: crystal.name,
    energy: 'A symbolic reminder for reflection and personal care.',
    chakra: 'Reflection',
    reason: 'Use this stone as a personal symbol if it is meaningful to you; it does not guarantee changes in well-being.',
    usage: 'Keep it nearby during reflection if you like. It is optional and does not replace practical or professional support.',
  })) };
}

type PersonalYearCopy = Pick<PersonalYearData, 'keyword' | 'theme' | 'overview' | 'career' | 'love' | 'spiritual' | 'warning' | 'affirmation'>;

const PERSONAL_YEAR_EN: Record<number, PersonalYearCopy> = {
  1: { keyword: 'New Beginnings', theme: 'Starting · Initiative · Independence', overview: 'A numerology 1 year can be a useful prompt to consider a fresh direction, define your priorities, and begin a manageable project. Treat this as a reflection framework, not a prediction that events will occur.', career: 'Review a goal or skill you would like to develop. Consider a small first step and the time, support, and resources it will require.', love: 'Notice how independence and connection can coexist. Talk with a partner about shared plans, or make room for new connections at a pace that feels comfortable.', spiritual: 'Reflect on which values you want to guide this next chapter. A short journaling or mindfulness routine may help you notice your own priorities.', warning: 'Starting many projects at once can make it hard to follow through. Set realistic expectations and avoid major financial decisions based only on excitement.', affirmation: 'I can begin with one thoughtful step and adjust as I learn.' },
  2: { keyword: 'Deeper Connections', theme: 'Relationships · Cooperation · Listening', overview: 'A numerology 2 year can invite reflection on communication, cooperation, and the quality of your relationships. Use the theme as a prompt rather than a guarantee about what will happen.', career: 'Collaboration and clear agreements may support your work. Confirm responsibilities and keep practical records for shared decisions.', love: 'Consider what helps you feel respected and heard. Share needs directly while maintaining boundaries and allowing relationships to develop at a healthy pace.', spiritual: 'Notice your own needs alongside the needs of others. Quiet reflection can help you distinguish your feelings from the atmosphere around you.', warning: 'Avoid agreeing to things simply to prevent disagreement. Protect time for rest and do not take responsibility for other people’s emotions.', affirmation: 'I can cooperate while honoring my own needs and boundaries.' },
  3: { keyword: 'Creative Expression', theme: 'Creativity · Communication · Enjoyment', overview: 'A numerology 3 year can be a prompt to make room for creativity, communication, and enjoyable experiences. It does not guarantee recognition or financial success.', career: 'Share a project, practice a skill, or explore a creative idea at a realistic scale. Consider the costs and commitments before turning a hobby into work.', love: 'Make time for conversation and shared activities. Be sincere about your feelings rather than relying on charm or avoiding difficult topics.', spiritual: 'Creative practice, music, or journaling can help you explore what matters to you. Enjoyment and reflection do not need to be earned through productivity.', warning: 'Many appealing ideas can compete for your attention. Choose a few priorities and set limits on spending and commitments.', affirmation: 'I make room for honest expression and meaningful enjoyment.' },
  4: { keyword: 'Building Foundations', theme: 'Structure · Practice · Long-Term Plans', overview: 'A numerology 4 year can prompt attention to routines, practical foundations, and sustained effort. Progress may be gradual, and circumstances can affect what is possible.', career: 'Review your workflow, finances, and longer-term goals. Break projects into manageable steps and leave room to revise the plan.', love: 'Discuss everyday responsibilities and expectations. Consistency can support a relationship, while flexibility helps it adapt to change.', spiritual: 'Small, repeatable practices may help you reflect. Include rest and physical well-being rather than treating discipline as constant effort.', warning: 'Overwork and perfectionism can undermine the stability you are trying to create. Schedule breaks and ask for help when needed.', affirmation: 'I build steady foundations through practical, sustainable steps.' },
  5: { keyword: 'Change and Exploration', theme: 'Flexibility · Variety · Learning', overview: 'A numerology 5 year can be a prompt to examine where flexibility or new experiences may be useful. Consider risks and responsibilities before making significant changes.', career: 'Explore a new skill or approach in a low-risk way. Review contracts, costs, and practical details before taking on a new commitment.', love: 'Talk about changing needs and make space for individual interests. New experiences can be enjoyable when both people feel comfortable.', spiritual: 'Curiosity and reflection can help you learn from experience. Keep routines that support your health even as other parts of life change.', warning: 'Impulsive decisions or too many simultaneous commitments may create stress. Pause to consider likely outcomes before acting.', affirmation: 'I can stay curious, make informed choices, and adapt.' },
  6: { keyword: 'Care and Responsibility', theme: 'Relationships · Home · Balance', overview: 'A numerology 6 year can invite reflection on care, shared responsibilities, and belonging. Consider how to support others while also protecting your own capacity.', career: 'Review how responsibilities are distributed at work. Clear expectations and reasonable limits can make support more sustainable.', love: 'Discuss shared needs and practical responsibilities. Care is healthiest when it is mutual and freely chosen.', spiritual: 'Practice compassion toward yourself as well as others. Reflection can help you notice when you need rest or support.', warning: 'Taking on too much can lead to resentment or exhaustion. You are allowed to set limits and ask others to contribute.', affirmation: 'I offer care with compassion and respect my own limits.' },
  7: { keyword: 'Reflection and Learning', theme: 'Study · Insight · Quiet Time', overview: 'A numerology 7 year can be a prompt for study, reflection, and examining assumptions. Treat insights as questions to explore, not as certain predictions.', career: 'Set aside time to deepen a useful skill or review a complex project. Balance research with practical action and feedback.', love: 'Allow space for reflection while communicating clearly. Solitude can be restorative, but avoid using distance to leave important conversations unresolved.', spiritual: 'Journaling, reading, or mindfulness can support self-reflection. Keep your own judgment and seek qualified help when appropriate.', warning: 'Too much analysis or isolation can make it harder to act or stay connected. Set a time to review what you have learned.', affirmation: 'I make time to reflect and use what I learn thoughtfully.' },
  8: { keyword: 'Resources and Responsibility', theme: 'Planning · Work · Accountability', overview: 'A numerology 8 year can prompt reflection on resources, responsibility, and long-term goals. It is not a promise of financial gain; use evidence and sound advice for financial decisions.', career: 'Review priorities, workload, and the value of your contributions. Set measurable goals and seek feedback from people you trust.', love: 'Consider how responsibilities and decision-making are shared. Respect and communication matter more than control.', spiritual: 'Reflect on how influence and resources align with your values. Practical integrity can be part of personal growth.', warning: 'Avoid overcommitting or taking financial risks based on symbolic interpretations. Consider costs, uncertainty, and qualified advice.', affirmation: 'I can work toward my goals with integrity and practical judgment.' },
  9: { keyword: 'Completion and Perspective', theme: 'Review · Release · Transition', overview: 'A numerology 9 year can be a prompt to review what you have learned and consider what you may want to complete or change. Endings can bring mixed feelings, and not every hardship has a hidden purpose.', career: 'Review which commitments still fit your goals. Plan transitions carefully and complete important responsibilities where possible.', love: 'Acknowledge what is changing in relationships and communicate with care. You can grieve an ending without rushing into a new beginning.', spiritual: 'Reflection can help you decide what values or lessons you want to carry forward. You do not have to find meaning in every experience.', warning: 'Letting go does not require ignoring practical needs or forgiving before you are ready. Seek support through difficult transitions.', affirmation: 'I can honor what has passed and choose what I carry forward.' },
};

export function localizePersonalYearData(data: PersonalYearData): PersonalYearData {
  const copy = PERSONAL_YEAR_EN[data.number];
  if (!copy) return data;
  const quarterLabels = ['First Quarter', 'Second Quarter', 'Third Quarter', 'Fourth Quarter'];
  const yearContext: Record<number, string> = {
    1: 'The year-one theme emphasizes initiative and the beginning of a new cycle. You might use it to clarify what matters to you, test an idea, and take ownership of choices that are genuinely yours. Independence does not require doing everything alone: collaboration, feedback, and asking for help can strengthen a new start. Let progress come from considered action rather than pressure to transform every part of life at once.',
    2: 'The year-two theme emphasizes cooperation, patience, and emotional awareness. You might use it to notice how trust develops through consistent communication, mutual effort, and respect for different needs. Sensitivity can help you listen, but it does not make you responsible for managing everyone else’s feelings. Keep your own preferences visible, ask for clarity when needed, and let important relationships grow at a pace that feels safe and reciprocal.',
    3: 'The year-three theme emphasizes expression, creativity, and connection. You might use it to share ideas, make time for enjoyable activities, and give a developing skill room to grow. Enthusiasm is valuable, but it is easier to sustain when you choose priorities and protect time for follow-through. Let creativity be meaningful in its own right rather than measuring every effort by attention, recognition, or financial results.',
    4: 'The year-four theme emphasizes structure, consistency, and practical foundations. You might use it to review routines, break larger responsibilities into workable steps, and create systems that fit your actual life. Reliable progress does not require perfection or relentless effort. Leave room for rest, changing circumstances, and help from others; a flexible structure is often more sustainable than a rigid plan that becomes difficult to maintain.',
    5: 'The year-five theme emphasizes flexibility, exploration, and learning through experience. You might use it to consider new options without assuming that every change is automatically beneficial. Small experiments can provide useful information while keeping risks manageable. Before changing a major commitment, review the practical effects on your finances, health, relationships, and responsibilities. Curiosity and stability can coexist when you make changes deliberately and keep supports that matter.',
    6: 'The year-six theme emphasizes care, belonging, and shared responsibility. You might use it to notice how support is given and received at home, at work, and in close relationships. Caring for others does not require ignoring your own capacity, and setting limits does not mean you care less. Shared expectations, honest conversations, and time for rest can help make care more mutual and sustainable.',
    7: 'The year-seven theme emphasizes reflection, study, and time to reconsider assumptions. You might use it to deepen your understanding of a subject or listen more closely to your own responses. Solitude can be restorative when it is chosen, while too much withdrawal can make support harder to access. Balance research and reflection with practical action, ordinary connection, and qualified guidance when a decision has significant consequences.',
    8: 'The year-eight theme emphasizes responsibility, resources, and the use of influence. You might use it to review goals, understand the value of your work, and consider whether your decisions reflect your principles. Symbolic themes cannot promise financial success. Make consequential choices with current information, realistic estimates, and qualified advice, while remembering that achievement is most sustainable when it also leaves room for wellbeing and fair relationships.',
    9: 'The year-nine theme emphasizes review, completion, and transition. You might use it to decide which commitments still fit and what you are ready to finish, while allowing complicated feelings about change to take time. Letting go does not mean denying grief, overlooking practical needs, or forcing forgiveness. Keep the lessons that remain useful, seek support through difficult transitions, and approach new beginnings when you feel ready.',
  };
  const sectionDevelopment: Record<keyof Pick<PersonalYearData, 'overview' | 'career' | 'love' | 'spiritual' | 'warning'>, string> = {
    overview: 'As you reflect on this theme, consider the parts of life where it feels relevant and the parts where it does not. A numerology cycle can offer language for reviewing priorities, but it cannot establish what will happen or determine the right choice for you. Write down one hope, one constraint, and one question you still need to answer. Revisit them as circumstances change, and let your own experience, values, and reliable information shape the next step.',
    career: 'For a practical check-in, identify one work priority and define what progress would look like in observable terms. Consider the time, money, skills, and cooperation it will require, then choose a first step that is small enough to complete and useful enough to teach you something. Keep agreements clear, review workload before accepting more, and seek feedback from people who understand the situation. For major employment or financial decisions, compare realistic options and consult qualified support rather than relying on a symbolic forecast.',
    love: 'In relationships, the most useful guidance is often a direct conversation rather than an assumption about what another person feels or what the future holds. Name what you need, listen to the other person’s perspective, and discuss boundaries and shared responsibilities with care. If you are single, you can remain open to meeting people without treating a particular year as a promise of romance. Give trust time to develop, notice whether respect is mutual, and seek support if a relationship feels unsafe or persistently distressing.',
    spiritual: 'For personal reflection, choose a simple practice you can approach with curiosity, such as journaling, quiet breathing, reading, time in nature, or speaking with someone you trust. Ask what the theme brings to mind, what evidence supports your interpretation, and what alternative explanations might also fit. You do not need to accept every spiritual claim or make a major change to benefit from reflection. Keep practices that support your wellbeing, and seek qualified professional care for health concerns or difficult experiences.',
    warning: 'Use this section as a reminder to pause and check the facts, not as a reason to expect something bad. Before making a consequential commitment, review likely costs, possible downsides, timing, and who else may be affected. Avoid decisions made under pressure, and give yourself permission to ask questions or take time. Maintain routines that support your health, set boundaries around your capacity, and contact qualified professionals when an issue involves finances, health, legal matters, or personal safety.',
  };
  const affirmationAdditions: Record<number, string> = {
    1: 'I can welcome a new beginning without needing to have every answer today.',
    2: 'I can stay connected to myself while building trust and cooperation with others.',
    3: 'I can express myself honestly and give my priorities room to grow.',
    4: 'I can build dependable foundations one flexible, sustainable step at a time.',
    5: 'I can explore change thoughtfully while protecting what supports my wellbeing.',
    6: 'I can offer care generously while including my own needs and limits.',
    7: 'I can make space for reflection and stay connected to useful support.',
    8: 'I can work toward meaningful goals with integrity, care, and sound judgment. I can also protect time for rest and relationships.',
    9: 'I can honor what is ending and choose what I am ready to carry forward.',
  };
  const expandedCopy = {
    ...copy,
    overview: `${copy.overview}\n\n${yearContext[data.number]}\n\n${sectionDevelopment.overview}`,
    career: `${copy.career}\n\n${yearContext[data.number]}\n\n${sectionDevelopment.career}`,
    love: `${copy.love}\n\n${yearContext[data.number]}\n\n${sectionDevelopment.love}`,
    spiritual: `${copy.spiritual}\n\n${yearContext[data.number]}\n\n${sectionDevelopment.spiritual}`,
    warning: `${copy.warning}\n\n${yearContext[data.number]}\n\n${sectionDevelopment.warning}`,
    affirmation: `${copy.affirmation} ${affirmationAdditions[data.number]}`,
  };
  const quarterFocus = [
    'Set a manageable intention and identify a first step. Choose one realistic priority, note what support or information you need, and begin at a pace you can maintain.',
    'Review progress and adjust your plan to fit current circumstances. Talk through shared plans where relevant, and use what you have learned to choose a practical next step.',
    'Check your workload and make room for recovery or support. Notice what has changed, protect time for rest, and adjust before adding new commitments.',
    'Reflect on what you learned and decide what to carry into the next year. Complete practical loose ends and choose what you want to continue, change, or leave behind.',
  ];
  return {
    ...data,
    ...expandedCopy,
    crystals: data.crystals.map((crystal) => ({ ...crystal, nameZh: crystal.name, reason: 'A personal symbol for reflection; it does not guarantee an outcome.' })),
    quarters: data.quarters.map((quarter, index) => ({
      ...quarter,
      label: `${quarterLabels[index] ?? 'Quarter'} (${index + 1})`,
      energy: ['Planning', 'Steady Progress', 'Review', 'Integration'][index] ?? 'Reflection',
      focus: quarterFocus[index] ?? 'Review your priorities and choose a realistic next step.',
    })),
  };
}
